name: Prueba

on:
  push:
    branches:
      - main

jobs:
  hello_prueba:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the message
        run: |
          echo "Hola esto es una Prueba!!

        