name: Prueba

on:
  push:
    branches:
      - main

jobs:
  hello_prueba:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the message
        run: |
          echo "Hola esto es una Prueba!!"
          echo "Otra línea si quieres"
      - name: Dime la fecha
        run: date
      - name: Dime el nombre
        run: whoami
      - name: Archivos
        run: ls -l

        